[package]

name = "speedtest-rust"
version = "0.0.1"
authors = ["Nelson Chen <crazysim@gmail.com>"]

[dependencies]
time = "0.1"
hyper = "0.6"
log = "0.3"
env_logger = "0.3"
threadpool = "0.1"

[dependencies.xml-rs]
version = "*"
