[package]
name = "speedtest-rs"
version = "0.0.3"
authors = ["Nelson Chen <crazysim@gmail.com>"]
exclude = [
    "tests/config/*",
]
description = "Speedtest.net testing utility and crate"
license = "MIT"
repository = "https://github.com/nelsonjchen/speedtest-rs"

[dependencies]
time = "0.1"
hyper = "0.6"
log = "0.3"
env_logger = "0.3"
clap = "1.4"
xml-rs = "0.2"
