[package]

name = "speedtest-rust"
version = "0.0.1"
authors = ["Nelson Chen <crazysim@gmail.com>"]

[dependencies.xml-rs]
git="https://github.com/netvl/xml-rs.git"

[dependencies.hyper]
git="https://github.com/hyperium/hyper.git"
