on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
name: Usage Demo

jobs:
  usage-demo:
    name: "Usage Demo"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --features=${{ matrix.features }}

      - uses: actions-rs/cargo@v1
        name: Run (Typical)
        with:
          command: run

      - uses: actions-rs/cargo@v1
        name: Run (CSV Output)
        with:
          command: run
          args: -- --csv
      - uses: actions-rs/cargo@v1
        name: Run (CSV Header)
        with:
          command: run
          args: -- --csv-header
